language: node_js
node_js:
  - '5'
  - '4'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: src
    node: '5'
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
